name: Broskii Bot Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # 3時間ごとに実行（調整可）

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install feedparser requests beautifulsoup4
      - env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python broskii_bot.py
